name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Restore
        run: dotnet restore
      - name: Run Tests
        run: dotnet test tests/EventModeling.Tests/EventModeling.Tests.fsproj --no-build
